<%@ Page Language="C#" AutoEventWireup="true" CodeFile="modify-database.aspx.cs" Inherits="Default4" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="Content/bootstrap.css" rel="stylesheet" />
    <link href="Content/main.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server" style="background-color:lightgreen">

    <div class="container">
         <div class="jumbotron">
                 <h1>Modify Database</h1>
         </div>
    </div>

    

        <asp:LinkButton ID="home" 
            runat="server" 
            style="font-family:'Century Schoolbook'; font-style:italic"
            CssClass="btn btn-warning"    
            OnClick="home_Click">
    <span aria-hidden="true" class="glyphicon glyphicon-menu-left"></span>Home
</asp:LinkButton>


    <div>
     
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        <br />
        <br />
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="2px" CellPadding="3" Font-Italic="True" Font-Names="Century Schoolbook" Font-Size="Medium" Height="187px" style="margin-left: 109px" Width="417px" OnRowEditing="GridView1_RowEditing" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AllowSorting="True" DataKeyNames="name" DataSourceID="SqlDataSource1" CellSpacing="2">
            <Columns>
                <asp:BoundField DataField="name" HeaderText="University Name" ReadOnly="True" SortExpression="name"/>
                <asp:BoundField DataField="founded" HeaderText="Founded On" SortExpression="founded" />
                <asp:BoundField DataField="gre" HeaderText="Gre Score" SortExpression="gre" />
                <asp:BoundField DataField="toefl" HeaderText="Toefl Score" SortExpression="toefl" />
                <asp:BoundField DataField="app_fee" HeaderText="Application Fee" SortExpression="app_fee" />
                <asp:BoundField DataField="ug_score" HeaderText="UnderGrad Score" SortExpression="ug_score" />
                <asp:BoundField DataField="annum_fee" HeaderText="Annual Fee" SortExpression="annum_fee" />
                <asp:BoundField DataField="acceptance_rate" HeaderText="Acceptance Rate" SortExpression="acceptance_rate" />
                <asp:BoundField DataField="stu_fac_ratio" HeaderText="Student Faculty Ratio" SortExpression="stu_fac_ratio" />
                <asp:BoundField DataField="stu_satis_rate" HeaderText="Student Satisfaction Rate" SortExpression="stu_satis_rate" />
                <asp:BoundField DataField="graduation_rate" HeaderText="Graduation Rate" SortExpression="graduation_rate" />
                <asp:BoundField DataField="rank" HeaderText="Rank" SortExpression="rank" />
                <asp:BoundField DataField="location" HeaderText="City" SortExpression="location" />
                <asp:BoundField DataField="state" HeaderText="State" SortExpression="state" />
                <asp:BoundField DataField="zipcode" HeaderText="ZipCode" SortExpression="zipcode" />
                <asp:BoundField DataField="latitude" HeaderText="Latitude" SortExpression="latitude" />
                <asp:BoundField DataField="longitude" HeaderText="Longitude" SortExpression="longitude" />
            </Columns>
            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:vm59ConnectionString2 %>" DeleteCommand="DELETE FROM [final] WHERE [name] = @name" InsertCommand="INSERT INTO [final] ([name], [founded], [gre], [toefl], [app_fee], [ug_score], [annum_fee], [acceptance_rate], [stu_fac_ratio], [stu_satis_rate], [graduation_rate], [rank], [location], [state], [zipcode], [latitude], [longitude]) VALUES (@name, @founded, @gre, @toefl, @app_fee, @ug_score, @annum_fee, @acceptance_rate, @stu_fac_ratio, @stu_satis_rate, @graduation_rate, @rank, @location, @state, @zipcode, @latitude, @longitude)" SelectCommand="SELECT * FROM [final]" UpdateCommand="UPDATE [final] SET [founded] = @founded, [gre] = @gre, [toefl] = @toefl, [app_fee] = @app_fee, [ug_score] = @ug_score, [annum_fee] = @annum_fee, [acceptance_rate] = @acceptance_rate, [stu_fac_ratio] = @stu_fac_ratio, [stu_satis_rate] = @stu_satis_rate, [graduation_rate] = @graduation_rate, [rank] = @rank, [location] = @location, [state] = @state, [zipcode] = @zipcode, [latitude] = @latitude, [longitude] = @longitude WHERE [name] = @name">
            <DeleteParameters>
                <asp:Parameter Name="name" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="founded" Type="Int32" />
                <asp:Parameter Name="gre" Type="Int32" />
                <asp:Parameter Name="toefl" Type="Int32" />
                <asp:Parameter Name="app_fee" Type="Int32" />
                <asp:Parameter Name="ug_score" Type="Double" />
                <asp:Parameter Name="annum_fee" Type="Int32" />
                <asp:Parameter Name="acceptance_rate" Type="Double" />
                <asp:Parameter Name="stu_fac_ratio" Type="Double" />
                <asp:Parameter Name="stu_satis_rate" Type="Double" />
                <asp:Parameter Name="graduation_rate" Type="Double" />
                <asp:Parameter Name="rank" Type="Int32" />
                <asp:Parameter Name="location" Type="String" />
                <asp:Parameter Name="state" Type="String" />
                <asp:Parameter Name="zipcode" Type="Int32" />
                <asp:Parameter Name="latitude" Type="Double" />
                <asp:Parameter Name="longitude" Type="Double" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="founded" Type="Int32" />
                <asp:Parameter Name="gre" Type="Int32" />
                <asp:Parameter Name="toefl" Type="Int32" />
                <asp:Parameter Name="app_fee" Type="Int32" />
                <asp:Parameter Name="ug_score" Type="Double" />
                <asp:Parameter Name="annum_fee" Type="Int32" />
                <asp:Parameter Name="acceptance_rate" Type="Double" />
                <asp:Parameter Name="stu_fac_ratio" Type="Double" />
                <asp:Parameter Name="stu_satis_rate" Type="Double" />
                <asp:Parameter Name="graduation_rate" Type="Double" />
                <asp:Parameter Name="rank" Type="Int32" />
                <asp:Parameter Name="location" Type="String" />
                <asp:Parameter Name="state" Type="String" />
                <asp:Parameter Name="zipcode" Type="Int32" />
                <asp:Parameter Name="latitude" Type="Double" />
                <asp:Parameter Name="longitude" Type="Double" />
                <asp:Parameter Name="name" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        
        <br />
    
    </div>
    </form>
</body>
</html>
